// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © MrHari
//@version=4

study("Pane1", overlay = false)

fastLength = 12
slowLength = 26
signalLength = 9

fastMA = ema(close, fastLength)
slowMA = ema(close, slowLength)
macd = fastMA - slowMA
signal = sma(macd, signalLength)
hist = macd - signal

plot(macd, title="MACD", color=color.blue, linewidth=1)
plot(signal, title="Signal Line", color=color.orange, linewidth=1)
plot(hist, title="Histogram", color=color.black, style=plot.style_histogram, linewidth=2)
hline(0, '0 Line', linestyle=hline.style_solid, linewidth=1, color=color.black)


